/* Auto-generated by js/svg_to_js_generator.mjs from dataset/task1/000.svg. */
const SVG_STRING = `<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="432pt" height="432pt" viewBox="0 0 432 432" xmlns="http://www.w3.org/2000/svg" version="1.1">
 <metadata>
  <rdf:RDF xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
   <cc:Work>
    <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
    <dc:date>2026-01-13T20:30:34.058373</dc:date>
    <dc:format>image/svg+xml</dc:format>
    <dc:creator>
     <cc:Agent>
      <dc:title>Matplotlib v3.10.8, https://matplotlib.org/</dc:title>
     </cc:Agent>
    </dc:creator>
   </cc:Work>
  </rdf:RDF>
 </metadata>
 <defs>
  <style type="text/css">*{stroke-linejoin: round; stroke-linecap: butt}</style>
 </defs>
 <g id="figure_1">
  <g id="patch_1">
   <path d="M 0 432 
L 432 432 
L 432 0 
L 0 0 
z
" style="fill: #ffffff"/>
  </g>
  <g id="axes_1">
   <g id="patch_2">
    <path d="M 54 384.48 
L 388.8 384.48 
L 388.8 51.84 
L 54 51.84 
z
" style="fill: #ffffff"/>
   </g>
   <g id="PathCollection_1">
    <defs>
     <path id="C0_0_839dc671d6" d="M 0 3.872983 
C 1.027127 3.872983 2.012324 3.464901 2.738613 2.738613 
C 3.464901 2.012324 3.872983 1.027127 3.872983 -0 
C 3.872983 -1.027127 3.464901 -2.012324 2.738613 -2.738613 
C 2.012324 -3.464901 1.027127 -3.872983 0 -3.872983 
C -1.027127 -3.872983 -2.012324 -3.464901 -2.738613 -2.738613 
C -3.464901 -2.012324 -3.872983 -1.027127 -3.872983 0 
C -3.872983 1.027127 -3.464901 2.012324 -2.738613 2.738613 
C -2.012324 3.464901 -1.027127 3.872983 0 3.872983 
z
"/>
    </defs>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="213.406214" y="170.305972" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="220.886921" y="178.934285" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="214.128996" y="163.339775" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="210.365786" y="174.321732" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="198.066388" y="165.050463" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="204.182709" y="152.805501" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="208.243208" y="160.67523" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="196.879171" y="149.793588" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="209.126368" y="155.537408" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="219.094294" y="167.291939" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="202.348987" y="167.285471" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="214.425122" y="147.96031" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="194.862929" y="178.144854" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="221.372829" y="160.571868" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="216.401062" y="157.006995" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="224.641291" y="172.008559" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="210.142343" y="165.530167" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="193.06581" y="158.5957" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="203.829667" y="179.371844" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="206.725736" y="168.614798" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="221.134864" y="152.653039" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="220.633089" y="187.556588" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="215.572594" y="177.33818" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="207.696387" y="182.254689" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="209.298267" y="189.961298" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="224.391195" y="166.651816" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="201.288447" y="172.637741" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="230.732986" y="176.526215" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="200.628882" y="159.50789" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="227.844945" y="187.776736" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="240.796299" y="253.731125" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="243.370539" y="238.599364" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="237.393796" y="246.022453" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="219.786144" y="238.748888" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="220.229587" y="254.668838" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="247.472753" y="249.925893" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="231.584496" y="259.9207" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="249.193004" y="242.346045" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="235.699144" y="240.031095" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="232.475667" y="249.712849" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="236.481447" y="258.094459" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="236.220464" y="252.235559" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="241.447103" y="243.383309" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="260.053022" y="247.702604" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="243.131641" y="248.698691" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="235.547601" y="223.365206" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="243.936113" y="259.358843" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="226.997535" y="240.487253" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="231.853262" y="243.8284" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="239.206777" y="214.754555" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="248.609793" y="227.60575" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="221.696562" y="246.292106" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="230.657908" y="228.188567" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="248.22013" y="255.351752" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="239.592968" y="262.896123" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="248.801012" y="263.660819" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="239.681223" y="229.273787" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="249.683304" y="235.103623" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="225.720382" y="255.113423" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="234.183022" y="234.988517" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="252.850049" y="244.945053" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="232.709777" y="266.529505" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="244.062703" y="233.018213" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="119.201541" y="302.959857" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="129.56163" y="306.59863" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="123.891147" y="291.400234" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="112.31967" y="295.530909" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="126.306677" y="300.178917" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="118.057467" y="308.106955" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="107.914894" y="297.529262" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="130.921531" y="295.637567" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="121.566384" y="295.69532" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="125.788069" y="313.966356" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="131.129441" y="285.907146" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="114.652488" y="300.498869" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="116.533945" y="292.510374" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="121.11534" y="282.94674" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="135.022242" y="309.432621" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="110.452956" y="315.0967" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="120.680854" y="316.114833" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="137.361098" y="318.323518" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="134.36406" y="299.79022" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="116.607515" y="281.226841" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="119.874137" y="288.48985" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="136.29394" y="293.466431" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="122.268207" y="276.382646" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="123.507825" y="309.651069" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="137.514143" y="304.973971" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="141.533253" y="306.587324" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="112.122395" y="273.673484" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="137.780049" y="286.625159" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="144.803472" y="291.922372" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="148.05741" y="301.028338" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="109.31948" y="305.532193" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="134.47045" y="279.843293" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="129.005922" y="290.859535" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="309.687006" y="116.352091" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="299.362096" y="111.13961" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="304.627907" y="122.686948" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="299.315031" y="118.617895" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="323.702506" y="115.351766" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="316.206453" y="110.060537" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="313.936938" y="124.404017" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="310.667772" y="145.942527" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="287.41395" y="91.649593" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="321.133594" y="134.938822" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="292.088078" y="127.583179" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="307.581222" y="139.500485" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="309.914777" y="127.093223" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="304.994141" y="102.975351" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="301.323455" y="131.947609" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="288.237091" y="119.056409" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="297.297256" y="127.815693" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="320.920829" y="111.436244" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="308.967871" y="132.914515" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="294.11461" y="137.93023" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="329.609529" y="107.399772" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="324.761293" y="122.479108" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="323.962062" y="129.721208" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="314.374098" y="118.330286" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="285.19683" y="134.401182" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="314.604998" y="136.690815" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
    <g clip-path="url(#p9a5809dc5b)">
     <use xlink:href="#C0_0_839dc671d6" x="303.176819" y="150.369071" style="fill: #1f77b4; fill-opacity: 0.8"/>
    </g>
   </g>
   <g id="matplotlib.axis_1">
    <g id="xtick_1">
     <g id="line2d_1">
      <path d="M 99.294568 384.48 
L 99.294568 51.84 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_2">
      <defs>
       <path id="mbe8d2129cb" d="M 0 0 
L 0 3.5 
" style="stroke: #000000; stroke-width: 0.8"/>
      </defs>
      <g>
       <use xlink:href="#mbe8d2129cb" x="99.294568" y="384.48" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_1">
      <!-- 0 -->
      <g transform="translate(96.113318 399.078438) scale(0.1 -0.1)">
       <defs>
        <path id="DejaVuSans-30" d="M 2034 4250 
Q 1547 4250 1301 3770 
Q 1056 3291 1056 2328 
Q 1056 1369 1301 889 
Q 1547 409 2034 409 
Q 2525 409 2770 889 
Q 3016 1369 3016 2328 
Q 3016 3291 2770 3770 
Q 2525 4250 2034 4250 
z
M 2034 4750 
Q 2819 4750 3233 4129 
Q 3647 3509 3647 2328 
Q 3647 1150 3233 529 
Q 2819 -91 2034 -91 
Q 1250 -91 836 529 
Q 422 1150 422 2328 
Q 422 3509 836 4129 
Q 1250 4750 2034 4750 
z
" transform="scale(0.015625)"/>
       </defs>
       <use xlink:href="#DejaVuSans-30"/>
      </g>
     </g>
    </g>
    <g id="xtick_2">
     <g id="line2d_3">
      <path d="M 152.112351 384.48 
L 152.112351 51.84 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_4">
      <g>
       <use xlink:href="#mbe8d2129cb" x="152.112351" y="384.48" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_2">
      <!-- 20 -->
      <g transform="translate(145.749851 399.078438) scale(0.1 -0.1)">
       <defs>
        <path id="DejaVuSans-32" d="M 1228 531 
L 3431 531 
L 3431 0 
L 469 0 
L 469 531 
Q 828 903 1448 1529 
Q 2069 2156 2228 2338 
Q 2531 2678 2651 2914 
Q 2772 3150 2772 3378 
Q 2772 3750 2511 3984 
Q 2250 4219 1831 4219 
Q 1534 4219 1204 4116 
Q 875 4013 500 3803 
L 500 4441 
Q 881 4594 1212 4672 
Q 1544 4750 1819 4750 
Q 2544 4750 2975 4387 
Q 3406 4025 3406 3419 
Q 3406 3131 3298 2873 
Q 3191 2616 2906 2266 
Q 2828 2175 2409 1742 
Q 1991 1309 1228 531 
z
" transform="scale(0.015625)"/>
       </defs>
       <use xlink:href="#DejaVuSans-32"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
      </g>
     </g>
    </g>
    <g id="xtick_3">
     <g id="line2d_5">
      <path d="M 204.930134 384.48 
L 204.930134 51.84 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_6">
      <g>
       <use xlink:href="#mbe8d2129cb" x="204.930134" y="384.48" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_3">
      <!-- 40 -->
      <g transform="translate(198.567634 399.078438) scale(0.1 -0.1)">
       <defs>
        <path id="DejaVuSans-34" d="M 2419 4116 
L 825 1625 
L 2419 1625 
L 2419 4116 
z
M 2253 4666 
L 3047 4666 
L 3047 1625 
L 3713 1625 
L 3713 1100 
L 3047 1100 
L 3047 0 
L 2419 0 
L 2419 1100 
L 313 1100 
L 313 1709 
L 2253 4666 
z
" transform="scale(0.015625)"/>
       </defs>
       <use xlink:href="#DejaVuSans-34"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
      </g>
     </g>
    </g>
    <g id="xtick_4">
     <g id="line2d_7">
      <path d="M 257.747917 384.48 
L 257.747917 51.84 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_8">
      <g>
       <use xlink:href="#mbe8d2129cb" x="257.747917" y="384.48" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_4">
      <!-- 60 -->
      <g transform="translate(251.385417 399.078438) scale(0.1 -0.1)">
       <defs>
        <path id="DejaVuSans-36" d="M 2113 2584 
Q 1688 2584 1439 2293 
Q 1191 2003 1191 1497 
Q 1191 994 1439 701 
Q 1688 409 2113 409 
Q 2538 409 2786 701 
Q 3034 994 3034 1497 
Q 3034 2003 2786 2293 
Q 2538 2584 2113 2584 
z
M 3366 4563 
L 3366 3988 
Q 3128 4100 2886 4159 
Q 2644 4219 2406 4219 
Q 1781 4219 1451 3797 
Q 1122 3375 1075 2522 
Q 1259 2794 1537 2939 
Q 1816 3084 2150 3084 
Q 2853 3084 3261 2657 
Q 3669 2231 3669 1497 
Q 3669 778 3244 343 
Q 2819 -91 2113 -91 
Q 1303 -91 875 529 
Q 447 1150 447 2328 
Q 447 3434 972 4092 
Q 1497 4750 2381 4750 
Q 2619 4750 2861 4703 
Q 3103 4656 3366 4563 
z
" transform="scale(0.015625)"/>
       </defs>
       <use xlink:href="#DejaVuSans-36"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
      </g>
     </g>
    </g>
    <g id="xtick_5">
     <g id="line2d_9">
      <path d="M 310.5657 384.48 
L 310.5657 51.84 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_10">
      <g>
       <use xlink:href="#mbe8d2129cb" x="310.5657" y="384.48" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_5">
      <!-- 80 -->
      <g transform="translate(304.2032 399.078438) scale(0.1 -0.1)">
       <defs>
        <path id="DejaVuSans-38" d="M 2034 2216 
Q 1584 2216 1326 1975 
Q 1069 1734 1069 1313 
Q 1069 891 1326 650 
Q 1584 409 2034 409 
Q 2484 409 2743 651 
Q 3003 894 3003 1313 
Q 3003 1734 2745 1975 
Q 2488 2216 2034 2216 
z
M 1403 2484 
Q 997 2584 770 2862 
Q 544 3141 544 3541 
Q 544 4100 942 4425 
Q 1341 4750 2034 4750 
Q 2731 4750 3128 4425 
Q 3525 4100 3525 3541 
Q 3525 3141 3298 2862 
Q 3072 2584 2669 2484 
Q 3125 2378 3379 2068 
Q 3634 1759 3634 1313 
Q 3634 634 3220 271 
Q 2806 -91 2034 -91 
Q 1263 -91 848 271 
Q 434 634 434 1313 
Q 434 1759 690 2068 
Q 947 2378 1403 2484 
z
M 1172 3481 
Q 1172 3119 1398 2916 
Q 1625 2713 2034 2713 
Q 2441 2713 2670 2916 
Q 2900 3119 2900 3481 
Q 2900 3844 2670 4047 
Q 2441 4250 2034 4250 
Q 1625 4250 1398 4047 
Q 1172 3844 1172 3481 
z
" transform="scale(0.015625)"/>
       </defs>
       <use xlink:href="#DejaVuSans-38"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
      </g>
     </g>
    </g>
    <g id="xtick_6">
     <g id="line2d_11">
      <path d="M 363.383483 384.48 
L 363.383483 51.84 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_12">
      <g>
       <use xlink:href="#mbe8d2129cb" x="363.383483" y="384.48" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_6">
      <!-- 100 -->
      <g transform="translate(353.839733 399.078438) scale(0.1 -0.1)">
       <defs>
        <path id="DejaVuSans-31" d="M 794 531 
L 1825 531 
L 1825 4091 
L 703 3866 
L 703 4441 
L 1819 4666 
L 2450 4666 
L 2450 531 
L 3481 531 
L 3481 0 
L 794 0 
L 794 531 
z
" transform="scale(0.015625)"/>
       </defs>
       <use xlink:href="#DejaVuSans-31"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(127.246094 0)"/>
      </g>
     </g>
    </g>
   </g>
   <g id="matplotlib.axis_2">
    <g id="ytick_1">
     <g id="line2d_13">
      <path d="M 54 380.117801 
L 388.8 380.117801 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_14">
      <defs>
       <path id="mbf639b0d2a" d="M 0 0 
L -3.5 0 
" style="stroke: #000000; stroke-width: 0.8"/>
      </defs>
      <g>
       <use xlink:href="#mbf639b0d2a" x="54" y="380.117801" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_7">
      <!-- 0 -->
      <g transform="translate(40.6375 383.91702) scale(0.1 -0.1)">
       <use xlink:href="#DejaVuSans-30"/>
      </g>
     </g>
    </g>
    <g id="ytick_2">
     <g id="line2d_15">
      <path d="M 54 316.353923 
L 388.8 316.353923 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_16">
      <g>
       <use xlink:href="#mbf639b0d2a" x="54" y="316.353923" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_8">
      <!-- 20 -->
      <g transform="translate(34.275 320.153141) scale(0.1 -0.1)">
       <use xlink:href="#DejaVuSans-32"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
      </g>
     </g>
    </g>
    <g id="ytick_3">
     <g id="line2d_17">
      <path d="M 54 252.590044 
L 388.8 252.590044 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_18">
      <g>
       <use xlink:href="#mbf639b0d2a" x="54" y="252.590044" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_9">
      <!-- 40 -->
      <g transform="translate(34.275 256.389262) scale(0.1 -0.1)">
       <use xlink:href="#DejaVuSans-34"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
      </g>
     </g>
    </g>
    <g id="ytick_4">
     <g id="line2d_19">
      <path d="M 54 188.826165 
L 388.8 188.826165 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_20">
      <g>
       <use xlink:href="#mbf639b0d2a" x="54" y="188.826165" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_10">
      <!-- 60 -->
      <g transform="translate(34.275 192.625383) scale(0.1 -0.1)">
       <use xlink:href="#DejaVuSans-36"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
      </g>
     </g>
    </g>
    <g id="ytick_5">
     <g id="line2d_21">
      <path d="M 54 125.062286 
L 388.8 125.062286 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_22">
      <g>
       <use xlink:href="#mbf639b0d2a" x="54" y="125.062286" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_11">
      <!-- 80 -->
      <g transform="translate(34.275 128.861505) scale(0.1 -0.1)">
       <use xlink:href="#DejaVuSans-38"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
      </g>
     </g>
    </g>
    <g id="ytick_6">
     <g id="line2d_23">
      <path d="M 54 61.298407 
L 388.8 61.298407 
" clip-path="url(#p9a5809dc5b)" style="fill: none; stroke-dasharray: 2.96,1.28; stroke-dashoffset: 0; stroke: #b0b0b0; stroke-opacity: 0.3; stroke-width: 0.8"/>
     </g>
     <g id="line2d_24">
      <g>
       <use xlink:href="#mbf639b0d2a" x="54" y="61.298407" style="stroke: #000000; stroke-width: 0.8"/>
      </g>
     </g>
     <g id="text_12">
      <!-- 100 -->
      <g transform="translate(27.9125 65.097626) scale(0.1 -0.1)">
       <use xlink:href="#DejaVuSans-31"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(63.623047 0)"/>
       <use xlink:href="#DejaVuSans-30" transform="translate(127.246094 0)"/>
      </g>
     </g>
    </g>
   </g>
   <g id="patch_3">
    <path d="M 54 384.48 
L 54 51.84 
" style="fill: none; stroke: #000000; stroke-width: 0.8; stroke-linejoin: miter; stroke-linecap: square"/>
   </g>
   <g id="patch_4">
    <path d="M 388.8 384.48 
L 388.8 51.84 
" style="fill: none; stroke: #000000; stroke-width: 0.8; stroke-linejoin: miter; stroke-linecap: square"/>
   </g>
   <g id="patch_5">
    <path d="M 54 384.48 
L 388.8 384.48 
" style="fill: none; stroke: #000000; stroke-width: 0.8; stroke-linejoin: miter; stroke-linecap: square"/>
   </g>
   <g id="patch_6">
    <path d="M 54 51.84 
L 388.8 51.84 
" style="fill: none; stroke: #000000; stroke-width: 0.8; stroke-linejoin: miter; stroke-linecap: square"/>
   </g>
   <g id="text_13">
    <!-- Base Distribution -->
    <g transform="translate(169.879688 45.84) scale(0.12 -0.12)">
     <defs>
      <path id="DejaVuSans-42" d="M 1259 2228 
L 1259 519 
L 2272 519 
Q 2781 519 3026 730 
Q 3272 941 3272 1375 
Q 3272 1813 3026 2020 
Q 2781 2228 2272 2228 
L 1259 2228 
z
M 1259 4147 
L 1259 2741 
L 2194 2741 
Q 2656 2741 2882 2914 
Q 3109 3088 3109 3444 
Q 3109 3797 2882 3972 
Q 2656 4147 2194 4147 
L 1259 4147 
z
M 628 4666 
L 2241 4666 
Q 2963 4666 3353 4366 
Q 3744 4066 3744 3513 
Q 3744 3084 3544 2831 
Q 3344 2578 2956 2516 
Q 3422 2416 3680 2098 
Q 3938 1781 3938 1306 
Q 3938 681 3513 340 
Q 3088 0 2303 0 
L 628 0 
L 628 4666 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-61" d="M 2194 1759 
Q 1497 1759 1228 1600 
Q 959 1441 959 1056 
Q 959 750 1161 570 
Q 1363 391 1709 391 
Q 2188 391 2477 730 
Q 2766 1069 2766 1631 
L 2766 1759 
L 2194 1759 
z
M 3341 1997 
L 3341 0 
L 2766 0 
L 2766 531 
Q 2569 213 2275 61 
Q 1981 -91 1556 -91 
Q 1019 -91 701 211 
Q 384 513 384 1019 
Q 384 1609 779 1909 
Q 1175 2209 1959 2209 
L 2766 2209 
L 2766 2266 
Q 2766 2663 2505 2880 
Q 2244 3097 1772 3097 
Q 1472 3097 1187 3025 
Q 903 2953 641 2809 
L 641 3341 
Q 956 3463 1253 3523 
Q 1550 3584 1831 3584 
Q 2591 3584 2966 3190 
Q 3341 2797 3341 1997 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-73" d="M 2834 3397 
L 2834 2853 
Q 2591 2978 2328 3040 
Q 2066 3103 1784 3103 
Q 1356 3103 1142 2972 
Q 928 2841 928 2578 
Q 928 2378 1081 2264 
Q 1234 2150 1697 2047 
L 1894 2003 
Q 2506 1872 2764 1633 
Q 3022 1394 3022 966 
Q 3022 478 2636 193 
Q 2250 -91 1575 -91 
Q 1294 -91 989 -36 
Q 684 19 347 128 
L 347 722 
Q 666 556 975 473 
Q 1284 391 1588 391 
Q 1994 391 2212 530 
Q 2431 669 2431 922 
Q 2431 1156 2273 1281 
Q 2116 1406 1581 1522 
L 1381 1569 
Q 847 1681 609 1914 
Q 372 2147 372 2553 
Q 372 3047 722 3315 
Q 1072 3584 1716 3584 
Q 2034 3584 2315 3537 
Q 2597 3491 2834 3397 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-65" d="M 3597 1894 
L 3597 1613 
L 953 1613 
Q 991 1019 1311 708 
Q 1631 397 2203 397 
Q 2534 397 2845 478 
Q 3156 559 3463 722 
L 3463 178 
Q 3153 47 2828 -22 
Q 2503 -91 2169 -91 
Q 1331 -91 842 396 
Q 353 884 353 1716 
Q 353 2575 817 3079 
Q 1281 3584 2069 3584 
Q 2775 3584 3186 3129 
Q 3597 2675 3597 1894 
z
M 3022 2063 
Q 3016 2534 2758 2815 
Q 2500 3097 2075 3097 
Q 1594 3097 1305 2825 
Q 1016 2553 972 2059 
L 3022 2063 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-20" transform="scale(0.015625)"/>
      <path id="DejaVuSans-44" d="M 1259 4147 
L 1259 519 
L 2022 519 
Q 2988 519 3436 956 
Q 3884 1394 3884 2338 
Q 3884 3275 3436 3711 
Q 2988 4147 2022 4147 
L 1259 4147 
z
M 628 4666 
L 1925 4666 
Q 3281 4666 3915 4102 
Q 4550 3538 4550 2338 
Q 4550 1131 3912 565 
Q 3275 0 1925 0 
L 628 0 
L 628 4666 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-69" d="M 603 3500 
L 1178 3500 
L 1178 0 
L 603 0 
L 603 3500 
z
M 603 4863 
L 1178 4863 
L 1178 4134 
L 603 4134 
L 603 4863 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-74" d="M 1172 4494 
L 1172 3500 
L 2356 3500 
L 2356 3053 
L 1172 3053 
L 1172 1153 
Q 1172 725 1289 603 
Q 1406 481 1766 481 
L 2356 481 
L 2356 0 
L 1766 0 
Q 1100 0 847 248 
Q 594 497 594 1153 
L 594 3053 
L 172 3053 
L 172 3500 
L 594 3500 
L 594 4494 
L 1172 4494 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-72" d="M 2631 2963 
Q 2534 3019 2420 3045 
Q 2306 3072 2169 3072 
Q 1681 3072 1420 2755 
Q 1159 2438 1159 1844 
L 1159 0 
L 581 0 
L 581 3500 
L 1159 3500 
L 1159 2956 
Q 1341 3275 1631 3429 
Q 1922 3584 2338 3584 
Q 2397 3584 2469 3576 
Q 2541 3569 2628 3553 
L 2631 2963 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-62" d="M 3116 1747 
Q 3116 2381 2855 2742 
Q 2594 3103 2138 3103 
Q 1681 3103 1420 2742 
Q 1159 2381 1159 1747 
Q 1159 1113 1420 752 
Q 1681 391 2138 391 
Q 2594 391 2855 752 
Q 3116 1113 3116 1747 
z
M 1159 2969 
Q 1341 3281 1617 3432 
Q 1894 3584 2278 3584 
Q 2916 3584 3314 3078 
Q 3713 2572 3713 1747 
Q 3713 922 3314 415 
Q 2916 -91 2278 -91 
Q 1894 -91 1617 61 
Q 1341 213 1159 525 
L 1159 0 
L 581 0 
L 581 4863 
L 1159 4863 
L 1159 2969 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-75" d="M 544 1381 
L 544 3500 
L 1119 3500 
L 1119 1403 
Q 1119 906 1312 657 
Q 1506 409 1894 409 
Q 2359 409 2629 706 
Q 2900 1003 2900 1516 
L 2900 3500 
L 3475 3500 
L 3475 0 
L 2900 0 
L 2900 538 
Q 2691 219 2414 64 
Q 2138 -91 1772 -91 
Q 1169 -91 856 284 
Q 544 659 544 1381 
z
M 1991 3584 
L 1991 3584 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-6f" d="M 1959 3097 
Q 1497 3097 1228 2736 
Q 959 2375 959 1747 
Q 959 1119 1226 758 
Q 1494 397 1959 397 
Q 2419 397 2687 759 
Q 2956 1122 2956 1747 
Q 2956 2369 2687 2733 
Q 2419 3097 1959 3097 
z
M 1959 3584 
Q 2709 3584 3137 3096 
Q 3566 2609 3566 1747 
Q 3566 888 3137 398 
Q 2709 -91 1959 -91 
Q 1206 -91 779 398 
Q 353 888 353 1747 
Q 353 2609 779 3096 
Q 1206 3584 1959 3584 
z
" transform="scale(0.015625)"/>
      <path id="DejaVuSans-6e" d="M 3513 2113 
L 3513 0 
L 2938 0 
L 2938 2094 
Q 2938 2591 2744 2837 
Q 2550 3084 2163 3084 
Q 1697 3084 1428 2787 
Q 1159 2491 1159 1978 
L 1159 0 
L 581 0 
L 581 3500 
L 1159 3500 
L 1159 2956 
Q 1366 3272 1645 3428 
Q 1925 3584 2291 3584 
Q 2894 3584 3203 3211 
Q 3513 2838 3513 2113 
z
" transform="scale(0.015625)"/>
     </defs>
     <use xlink:href="#DejaVuSans-42"/>
     <use xlink:href="#DejaVuSans-61" transform="translate(68.603516 0)"/>
     <use xlink:href="#DejaVuSans-73" transform="translate(129.882812 0)"/>
     <use xlink:href="#DejaVuSans-65" transform="translate(181.982422 0)"/>
     <use xlink:href="#DejaVuSans-20" transform="translate(243.505859 0)"/>
     <use xlink:href="#DejaVuSans-44" transform="translate(275.292969 0)"/>
     <use xlink:href="#DejaVuSans-69" transform="translate(352.294922 0)"/>
     <use xlink:href="#DejaVuSans-73" transform="translate(380.078125 0)"/>
     <use xlink:href="#DejaVuSans-74" transform="translate(432.177734 0)"/>
     <use xlink:href="#DejaVuSans-72" transform="translate(471.386719 0)"/>
     <use xlink:href="#DejaVuSans-69" transform="translate(512.5 0)"/>
     <use xlink:href="#DejaVuSans-62" transform="translate(540.283203 0)"/>
     <use xlink:href="#DejaVuSans-75" transform="translate(603.759766 0)"/>
     <use xlink:href="#DejaVuSans-74" transform="translate(667.138672 0)"/>
     <use xlink:href="#DejaVuSans-69" transform="translate(706.347656 0)"/>
     <use xlink:href="#DejaVuSans-6f" transform="translate(734.130859 0)"/>
     <use xlink:href="#DejaVuSans-6e" transform="translate(795.3125 0)"/>
    </g>
   </g>
  </g>
 </g>
 <defs>
  <clipPath id="p9a5809dc5b">
   <rect x="54" y="51.84" width="334.8" height="332.64"/>
  </clipPath>
 </defs>
</svg>
`;

export function createSvgElement() {
  const parser = new DOMParser();
  const doc = parser.parseFromString(SVG_STRING, "image/svg+xml");
  const parserError = doc.querySelector("parsererror");
  if (parserError) {
    throw new Error("Invalid SVG content: " + (parserError.textContent || "").trim());
  }

  return document.importNode(doc.documentElement, true);
}

export function mountSvg(target) {
  if (!(target instanceof Element)) {
    throw new TypeError("target must be a DOM Element");
  }

  const svg = createSvgElement();
  target.replaceChildren(svg);
  return svg;
}

const SVG_NS = "http://www.w3.org/2000/svg";
const XLINK_NS = "http://www.w3.org/1999/xlink";
const POINT_PATTERN = /[\(（]\s*(-?\d+(?:\.\d+)?)\s*[,，]\s*(-?\d+(?:\.\d+)?)\s*[\)）]/g;
const BRACKET_PAIR_PATTERN = /[\[【]\s*(-?\d+(?:\.\d+)?)\s*[,，]\s*(-?\d+(?:\.\d+)?)\s*[\]】]/g;

export function parseQuestion(question) {
  const points = [];
  const text = String(question || "");

  for (const match of text.matchAll(POINT_PATTERN)) {
    const x = Number.parseFloat(match[1]);
    const y = Number.parseFloat(match[2]);
    if (Number.isFinite(x) && Number.isFinite(y)) {
      points.push({ x, y });
    }
  }

  for (const match of text.matchAll(BRACKET_PAIR_PATTERN)) {
    const x = Number.parseFloat(match[1]);
    const y = Number.parseFloat(match[2]);
    if (Number.isFinite(x) && Number.isFinite(y)) {
      points.push({ x, y });
    }
  }

  return {
    new_points: points,
    raw: text,
  };
}

function extractAxisTicks(svgElement, axisId, tickPrefix, coordAttr) {
  const groups = svgElement.getElementsByTagNameNS(SVG_NS, "g");
  let axis = null;
  for (const group of groups) {
    if (group.getAttribute("id") === axisId) {
      axis = group;
      break;
    }
  }
  if (!axis) {
    return [];
  }

  function extractTickValueFromComment(textGroup) {
    const xml = new XMLSerializer().serializeToString(textGroup);
    const commentMatch = xml.match(/<!--\s*([+-]?\d+(?:\.\d+)?)\s*-->/);
    if (!commentMatch) {
      return Number.NaN;
    }
    return Number.parseFloat(commentMatch[1]);
  }

  const ticks = [];
  const tickGroups = axis.getElementsByTagNameNS(SVG_NS, "g");
  for (const group of tickGroups) {
    const groupId = group.getAttribute("id") || "";
    if (!groupId.startsWith(tickPrefix)) {
      continue;
    }

    const markerUse = group.querySelector("use");
    const labelGroup = group.querySelector('g[id^="text_"]');

    const pixel = Number.parseFloat(markerUse?.getAttribute(coordAttr) || "");
    const value = labelGroup ? extractTickValueFromComment(labelGroup) : Number.NaN;
    if (Number.isFinite(pixel) && Number.isFinite(value)) {
      ticks.push([pixel, value]);
    }
  }

  return ticks;
}

function interpolateAxis(value, ticks) {
  const ticksSorted = [...ticks].sort((a, b) => a[1] - b[1]);
  for (let i = 0; i < ticksSorted.length - 1; i += 1) {
    const [pixel1, data1] = ticksSorted[i];
    const [pixel2, data2] = ticksSorted[i + 1];
    if ((data1 <= value && value <= data2) || (data2 <= value && value <= data1)) {
      if (data2 === data1) {
        return pixel1;
      }
      const ratio = (value - data1) / (data2 - data1);
      return pixel1 + ratio * (pixel2 - pixel1);
    }
  }

  let pixel1 = ticksSorted[0][0];
  let data1 = ticksSorted[0][1];
  let pixel2 = ticksSorted[1][0];
  let data2 = ticksSorted[1][1];
  if (value < Math.min(data1, data2)) {
    if (data2 === data1) {
      return pixel1;
    }
    const ratio = (value - data1) / (data2 - data1);
    return pixel1 + ratio * (pixel2 - pixel1);
  }

  pixel1 = ticksSorted[ticksSorted.length - 2][0];
  data1 = ticksSorted[ticksSorted.length - 2][1];
  pixel2 = ticksSorted[ticksSorted.length - 1][0];
  data2 = ticksSorted[ticksSorted.length - 1][1];
  if (data2 === data1) {
    return pixel2;
  }
  const ratio = (value - data1) / (data2 - data1);
  return pixel1 + ratio * (pixel2 - pixel1);
}

function extractMarkerInfo(svgElement) {
  const pathCollection = svgElement.querySelector("g#PathCollection_1");
  if (!pathCollection) {
    return { href: null, clipPath: null };
  }

  const groupedUses = pathCollection.querySelectorAll("g use");
  for (const use of groupedUses) {
    const href =
      use.getAttribute("href") ||
      use.getAttribute("xlink:href") ||
      use.getAttributeNS(XLINK_NS, "href");
    if (href) {
      return { href, clipPath: use.parentElement?.getAttribute("clip-path") || null };
    }
  }

  const use = pathCollection.querySelector("use");
  if (!use) {
    return { href: null, clipPath: null };
  }
  const href =
    use.getAttribute("href") ||
    use.getAttribute("xlink:href") ||
    use.getAttributeNS(XLINK_NS, "href");
  return { href: href || null, clipPath: null };
}

function ensureUpdateGroup(svgElement) {
  const axes = svgElement.querySelector("g#axes_1");
  if (!axes) {
    throw new Error("SVG axes group not found.");
  }
  const existing = axes.querySelector("g#PathCollection_update");
  if (existing) {
    return existing;
  }
  const update = document.createElementNS(SVG_NS, "g");
  update.setAttribute("id", "PathCollection_update");
  axes.appendChild(update);
  return update;
}

function clearChildren(element) {
  while (element.firstChild) {
    element.removeChild(element.firstChild);
  }
}

export function updateScatterFromPoints(svgElement, points) {
  if (!(svgElement instanceof SVGElement)) {
    throw new TypeError("svgElement must be an SVGElement");
  }
  if (!Array.isArray(points) || points.length === 0) {
    throw new Error("No new points to render.");
  }

  const xTicks = extractAxisTicks(svgElement, "matplotlib.axis_1", "xtick_", "x");
  const yTicks = extractAxisTicks(svgElement, "matplotlib.axis_2", "ytick_", "y");
  if (xTicks.length < 2 || yTicks.length < 2) {
    throw new Error("Insufficient ticks to map data points.");
  }

  const pointsSvg = points.map((point) => {
    const xVal = Number.parseFloat(point.x);
    const yVal = Number.parseFloat(point.y);
    if (!Number.isFinite(xVal) || !Number.isFinite(yVal)) {
      throw new Error(`Invalid point: ${JSON.stringify(point)}`);
    }
    return {
      x: interpolateAxis(xVal, xTicks),
      y: interpolateAxis(yVal, yTicks),
    };
  });

  const { href, clipPath } = extractMarkerInfo(svgElement);
  const updateGroup = ensureUpdateGroup(svgElement);
  clearChildren(updateGroup);

  if (href) {
    for (const p of pointsSvg) {
      const g = document.createElementNS(SVG_NS, "g");
      if (clipPath) {
        g.setAttribute("clip-path", clipPath);
      }
      const use = document.createElementNS(SVG_NS, "use");
      use.setAttributeNS(XLINK_NS, "xlink:href", href);
      use.setAttribute("href", href);
      use.setAttribute("x", p.x.toFixed(6));
      use.setAttribute("y", p.y.toFixed(6));
      use.setAttribute("style", "fill: #ff1493; fill-opacity: 0.85");
      g.appendChild(use);
      updateGroup.appendChild(g);
    }
  } else {
    for (const p of pointsSvg) {
      const circle = document.createElementNS(SVG_NS, "circle");
      circle.setAttribute("cx", p.x.toFixed(6));
      circle.setAttribute("cy", p.y.toFixed(6));
      circle.setAttribute("r", "3.500000");
      circle.setAttribute(
        "style",
        "fill: #ff1493; stroke: #000000; stroke-width: 0.5; fill-opacity: 0.85"
      );
      updateGroup.appendChild(circle);
    }
  }

  return pointsSvg;
}

export function applyQuestionToSvg(svgElement, question) {
  const spec = parseQuestion(question);
  if (!spec.new_points.length) {
    throw new Error("No new points parsed from question.");
  }
  const pointsSvg = updateScatterFromPoints(svgElement, spec.new_points);
  return {
    update_spec: spec,
    points_svg: pointsSvg,
  };
}

function escapeForTemplateLiteral(input) {
  return input.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

export function buildJsModuleFromSvg(svgElement) {
  if (!(svgElement instanceof SVGElement)) {
    throw new TypeError("svgElement must be an SVGElement");
  }
  const serialized = new XMLSerializer().serializeToString(svgElement);
  const escaped = escapeForTemplateLiteral(serialized);

  return `const SVG_STRING = \`${escaped}\`;

export function createSvgElement() {
  const parser = new DOMParser();
  const doc = parser.parseFromString(SVG_STRING, "image/svg+xml");
  const parserError = doc.querySelector("parsererror");
  if (parserError) {
    throw new Error("Invalid SVG content: " + (parserError.textContent || "").trim());
  }
  return document.importNode(doc.documentElement, true);
}

export function mountSvg(target) {
  if (!(target instanceof Element)) {
    throw new TypeError("target must be a DOM Element");
  }
  const svg = createSvgElement();
  target.replaceChildren(svg);
  return svg;
}

export { SVG_STRING };
`;
}

export { SVG_STRING };
