#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

function escapeForTemplateLiteral(input) {
  return input
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function usage() {
  console.error(
    "Usage: node Edit-Verify-Reason/js/svg_to_js_generator.mjs <input-svg> [output-js]"
  );
}

const inputPath = process.argv[2] ?? "dataset/task1/000.svg";

if (!inputPath) {
  usage();
  process.exit(1);
}

const inputBaseName = path.basename(inputPath, path.extname(inputPath));
const outputPath = process.argv[3] ?? path.join("Edit-Verify-Reason", "js", `${inputBaseName}_svg.js`);

let svgSource;
try {
  svgSource = fs.readFileSync(inputPath, "utf8");
} catch (error) {
  console.error(`Failed to read SVG file: ${inputPath}`);
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}

const escapedSvg = escapeForTemplateLiteral(svgSource);

const generated = `/* Auto-generated by Edit-Verify-Reason/js/svg_to_js_generator.mjs from ${inputPath}. */
const SVG_STRING = \`${escapedSvg}\`;

export function createSvgElement() {
  const parser = new DOMParser();
  const doc = parser.parseFromString(SVG_STRING, "image/svg+xml");
  const parserError = doc.querySelector("parsererror");
  if (parserError) {
    throw new Error("Invalid SVG content: " + (parserError.textContent || "").trim());
  }

  return document.importNode(doc.documentElement, true);
}

export function mountSvg(target) {
  if (!(target instanceof Element)) {
    throw new TypeError("target must be a DOM Element");
  }

  const svg = createSvgElement();
  target.replaceChildren(svg);
  return svg;
}

export { SVG_STRING };
`;

try {
  fs.writeFileSync(outputPath, generated, "utf8");
} catch (error) {
  console.error(`Failed to write JS file: ${outputPath}`);
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}

console.log(`Generated ${outputPath}`);
